// 字体列表: https://blog.csdn.net/athrenzala/article/details/45430963
export default {
  'MAC-华文仿宋': 'STFangsong',
  'MAC-华文黑体': 'STHeiti',
  'MAC-华文细黑': 'STXihei',
  'MAC-华文楷体': 'STKaiti',
  'MAC-华文宋体': 'STSong',
  'MAC-儷黑 Pro': 'LiHei Pro Medium',
  'MAC-儷宋 Pro': 'LiSong Pro Light',
  'MAC-標楷體': 'BiauKai',
  'MAC-蘋果儷中黑': 'Apple LiGothic Medium',
  'MAC-蘋果儷細宋': 'Apple LiSung Light',
  'WIN-新細明體': 'PMingLiU',
  'WIN-細明體': 'MingLiU',
  'WIN-標楷體': 'DFKai- SB',
  'WIN-黑体': 'SimHei',
  'WIN-宋体': 'SimSun',
  'WIN-新宋体': 'NSimSun',
  'WIN-仿宋': 'FangSong',
  'WIN-楷体': 'KaiTi',
  'WIN-仿宋_GB2312': 'FangSong_GB2312',
  'WIN-楷体_GB2312': 'KaiTi_GB2312',
  'WIN-微軟正黑體': 'Microsoft JhengHei',
  'WIN-微软雅黑体': 'Microsoft YaHei',
};
